### ISSUE TITLE
TypeError: 'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by pamgnicba** [profLewis/geogg122#17]
smoothn2.py line 263 "Lambda = Lambda + (cos(pi*(arange(1,sizy[i]+1) - 1.)/sizy[i]).reshape(siz0))" gives the error "TypeError: 'numpy.float64' object cannot be interpreted as an integer".

The error is related to the reshape function and it happens with different input datasets, including the examples of the script.

Any help will be really appreciated.

**Comment by jgomezdans** [comment]
This can be fixed
